baseURL: "https://callvoiptelefoniewebsite.netlify.com"
LanguageCode: "nl"
title: "Callvoip"
theme: "callvoiptelefonie"
enableRobotsTXT: true
MetaDataFormat: "yaml"
params:
  cloudinary_base_url: "https://res.cloudinary.com/callvoip/image/upload"
taxonomies:
  category: categories
  onderdeel: onderdelen
  tag: tags
menu:
  top:
    - name: Status
      url: #
      weight: 1
    - name: Ondersteuning
      url: /ondersteuning
      weight: 2
    - name: Webshop
      url: #
      weight: 3
    - name: Login
      url: #
      weight: 4
