---
baseURL: https://callvoiptelefoniewebsite.netlify.com
LanguageCode: nl
title: Callvoip
theme: callvoiptelefonie
enableRobotsTXT: true
MetaDataFormat: yaml
params:
  cloudinary_base_url: https://res.cloudinary.com/callvoip/image/upload
taxonomies:
  category: categories
  onderdeel: onderdelen
  tag: tags
menu:
  top:
  - url: https://www.callvoiptelefonie.nl/mijncallvoip/
    name: Mijn Callvoip
    weight: 3
  - url: https://panel.callvoip.nl/login/panel
    name: Login
    weight: 5
  - url: "/ondersteuning"
    name: Ondersteuning
    weight: 2
  - url: https://callvoip.shop/
    name: Webshop
    weight: 4
  - url: https://status.kwebbl.com/
    name: Status
    weight: 1
  main:
  - name: Testimonials
    parent: Over ons
    weight: 5
  overons:
  - Name: Testimonials
    name: Testimonials
    weight: 5
