---
baseURL: https://callvoiptelefoniewebsite.netlify.com
LanguageCode: nl
title: Callvoip
theme: callvoiptelefonie
enableRobotsTXT: true
MetaDataFormat: yaml
params:
  cloudinary_base_url: https://res.cloudinary.com/callvoip/image/upload
taxonomies:
  category: categories
  onderdeel: onderdelen
  tag: tags
menu:
  top:
  - url: /status
    name: Status
    weight: 2
  - pre: external
    url: https://callvoip.shop/
    name: Webshop
    weight: 3
  - pre: external
    url: https://panel.callvoip.nl/login/panel
    name: Login
    weight: 7
  - url: "/ondersteuning"
    name: Support
    weight: 5
  footer:
  - url: https://www.callvoip.nl/download/callvoip/CallVoip_telefonie_aanvraagformulier.pdf
    name: Direct klant worden?
    weight: 6
  - url: "http://support.callvoip.nl:8040/"
    name: Hulp
    weight: 0
    pre: external
outputs:
  home:
  - HTML
  - JSON
