baseURL: "https://callvoiptelefoniewebsite.netlify.com"
LanguageCode: "nl-nl"
title: "Callvoip"
theme: "callvoiptelefonie"
enableRobotsTXT: true
params:
  cloudinary_base_url: "https://res.cloudinary.com/spinme/image/upload"
# menu:
#   main
