baseURL: "https://callvoiptelefoniewebsite.netlify.com"
languageCode: "en-us"
title: "callvoiptelefonie"
theme: "callvoiptelefonie"
cloudinary_base_url: "https://res.cloudinary.com/spinme"
# menu:
#   main
